package:
  name: postprocessing_variant_calls
  version: "0.1.2"

requirements:
  build:
    - python={{ python_version }}
    - make
    - poetry={{ poetry_version }}
  run:
    - python={{ python_version }}
    
source:
  path: ..

build:
  number: 0
  script: make deps-install

