name: Publish package to Conda

on:
    push:
        tags:
            - "*"
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Install Dependencies
              run: |
                  sudo apt-get update
                  sudo apt install build-essential
            - uses: actions/checkout@v2
            - name: publish-to-conda
              uses: maxibor/conda-package-publish-action@master
              with:
                  subdir: "conda"
                  anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
