name: test vardict filter command
on:
    push:
        branches: [main, develop, release/*]
        tags:
            - '*'
        paths-ignore:
            - "docs/**"
            - "**.md"
    pull_request:
        branches: "*"
        paths-ignore:
            - "docs/**"
            - "**.md"
jobs:
    test_post_processing:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.7, 3.8, 3.9]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Python 3.9.7
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9.7
            - name: Update test_post_processing Dependencies
              run: |
                  make deps-update
                  make deps-install
            - name: Pytest test_post_processing in Image
              run: |
                  pytest tests
