name: test_vardict
on:
  push:
    paths-ignore:
    - 'docs/**'
    - '**.md'
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**.md'
jobs:
  test_post_processing:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/msk-access/postprocessing_variant_calls:feature-add_inputs
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
    steps: 
        # get current branch 
        - name: Extract branch name
          run: |
            echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          id: extract_branch
       
        - name: Get current branch of postprocessing_variant_calls 
          run: |
            # install postprocessing_variant_calls 
            cd /opt
            mkdir postprocessing_variant_calls_test 
            cd postprocessing_variant_calls_test 
            git clone --recursive -b ${{ steps.extract_branch.outputs.branch }} https://github.com/msk-access/postprocessing_variant_calls.git 
            echo ls 
        
        - name: Refresh conda env 
          run: |
            cd /opt/postprocessing_variant_calls_test
            conda env update -f environment.yml
            make deps-install

        - name: Start conda env and Pytest 
          run: |
            eval "$(conda shell.bash hook)"
            conda activate vardict 
            cd /opt/postprocessing_variant_calls_test
            pytest tests
            
