name: test_post_processing
on:
  push:
    paths-ignore:
    - 'docs/**'
    - '**.md'
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**.md'
jobs:
  test_post_processing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/msk-access/postprocessing_variant_calls:re-project-layout
    steps: 
      # Checkout Repo 
      - name: Extract Branch Name 
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Checkout Extracted Branch in Image
        run: |
          cd /opt/postprocessing_variant_calls
          checkout ${{ steps.extract_branch.outputs.branch }}
      - name: Pytest test_post_processing in Image 
        run: |
          make deps-install
          pytest tests
          