name: test_post_processing
on:
  push:
    paths-ignore:
    - 'docs/**'
    - '**.md'
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**.md'
jobs:
  test_post_processing:
    runs-on: ${{ matrix.platform }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      max-parallel: 1
      matrix:
        platform: [debian-latest]
    steps: 
      # Checkout Repo 
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          submodules: recursive   
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.6.6
      - name: Install package dependencies
        run: | 
          conda install -c bioconda pyvcf
          make deps-install
      - name: Pytest test_post_processing
        run: |
          pytest tests
            
