name: test_post_processing
on:
  push:
    paths-ignore:
    - 'docs/**'
    - '**.md'
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**.md'
jobs:
  test_post_processing:
    runs-on: ${{ matrix.platform }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      max-parallel: 1
      matrix:
        platform: [ubuntu-latest]
    steps: 
      # Checkout Repo 
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          submodules: recursive
        
      - name: Install Conda 
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda env update --file environment.yml --name base
      - name: Create conda virtual environment
        run: | 
          conda env create -f environment.yml 

      - name: Install package dependencies
        run: | 
          eval "$(${CONDA}/bin/conda shell.bash hook)"
          conda activate vardict 
          make deps-install

      - name: Pytest test_post_processing
        run: |
          eval "$(${CONDA}/bin/conda shell.bash hook)" 
          conda activate vardict 
          pytest tests
            
