name: test_vardict
on:
  push:
    paths-ignore:
    - 'docs/**'
    - '**.md'
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**.md'
jobs:
  test_post_processing:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/msk-access/postprovessing_variant_calls:feature-add_inputs
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
    steps: 
        - name: Start conda env 
          run: |
            eval "$(conda shell.bash hook)"
            conda activate vardict 
        - name: Test with pytest
          run: |
            cd /opt/postprocessing_variant_calls
            pytest tests
